language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t yu8/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true yu8/docker-react npm run test